version: "3.8"
services:
  postgresql-zskarte:
    image: bitnami/postgresql:latest
    container_name: postgresql-zskarte
    restart: unless-stopped
    volumes:
      - ./data/postgresql:/bitnami/postgresql
    ports:
      - 55432:5432
    environment:
      - POSTGRESQL_PASSWORD=supersecret123
    networks:
      - zskarte

  pgadmin-zskarte:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-zskarte
    restart: unless-stopped
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - 7050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=info@zskarte.ch
      - PGADMIN_DEFAULT_PASSWORD=zskarte
    networks:
      - zskarte

networks:
  zskarte:
    driver: bridge