apiVersion: v1
kind: Service
metadata:
    name: "zskarteaks-eaa4"
    labels:
        app: "zskarteaks-eaa4"
spec:
    type: LoadBalancer
    ports:
    - port: 1337
      targetPort: 1337
      protocol: TCP
      name: http
    selector:
        app: "zskarteaks-eaa4"