apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${KUBERNETES_NAMESPACE}
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
    service: api
    stage: ${STAGE}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ${APP_NAME}
      service: api
      stage: ${STAGE}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
        service: api
        stage: ${STAGE}
    spec:
      containers:
      - name: ${APP_NAME}
        image: ${FULL_IMAGE_NAME}
        startupProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 60
          failureThreshold: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 3
          periodSeconds: 5
        env:
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: db_host
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: db_port
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: db_name
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: db_user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: db_password
        - name: DATABASE_SSL
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: db_ssl
        - name: ADMIN_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: admin_jwt_secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: jwt_secret
        - name: NODE_ENV
          value: production
        ports:
        - name: http
          containerPort: 1337
