apiVersion: v1
kind: Service
metadata:
  namespace: ${KUBERNETES_NAMESPACE}
  name: ${IMAGE_NAME}
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: $(imageName)
    service: api
    stage: ${STAGE}
