on:
  push:
    branches:
      - dev

env:
  KUBERNETES_NAMESPACE: zskarte-test-2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image to Docker Hub
        id: build-image
        run: |
          docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t zskarte/zskarte-server:${{ github.sha }} --label dockerfile-path=Dockerfile
          docker push zskarte/zskarte-server:${{ github.sha }}

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.aks_zskarteaks_kubeConfig }}

      - name: Create Namespace if not Present
        run: |
          namespacePresent=`kubectl get namespace | grep ${{ ev.KUBERNETES_NAMESPACE }} | wc -l`
          if [ $namespacePresent -eq 0 ]
          then
              echo `kubectl create namespace ${{ ev.KUBERNETES_NAMESPACE }}`
          fi

    # - uses: azure/k8s-deploy@v1.2
    #   with:
    #     namespace: zskarte-test
    #     manifests: |
    #       .azure/k8s/deployment.yml
    #       .azure/k8s/service.yml
    #     images: |
    #       zskarte.azurecr.io/zskarteaks:${{ github.sha }}
    #     imagepullsecrets: |
    #       zskarteaksdockerauth
