on:
  push:
    branches:
      - dev

env:
  STAGE: dev
  KUBERNETES_NAMESPACE: zskarte-dev
  IMAGE_NAME: zskarte/zskarte-server
  FULL_IMAGE_NAME: zskarte/zskarte-server:${{ github.sha }}
  LETSENCRYPT_STAGE: staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image to Docker Hub
        id: build-image
        run: |
          docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t ${{ env.IMAGE_NAME }} --label dockerfile-path=Dockerfile
          docker push ${{ env.IMAGE_NAME }}

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.aks_zskarteaks_kubeConfig }}

      - name: Create Namespace if not Present
        run: |
          namespacePresent=`kubectl get namespace | grep ${{ env.KUBERNETES_NAMESPACE }} | wc -l`
          if [ $namespacePresent -eq 0 ]
          then
              echo `kubectl create namespace ${{ env.KUBERNETES_NAMESPACE }}`
          fi

      - name: Replace and Apply Kubernetes Manifests
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        with:
          k8-config-file-paths: |
            .azure/k8s/deployment.yml
            .azure/k8s/service.yml
          replacement-method: defined
        env:
          IMAGE_TAG: ${{ github.sha }}
          CHANGE_CAUSE: ${{ github.event.release.tag_name }}


    # - uses: azure/k8s-deploy@v1.2
    #   with:
    #     namespace: zskarte-dev
    #     manifests: |
    #       .azure/k8s/deployment.yml
    #       .azure/k8s/service.yml
    #     images: |
    #       zskarte.azurecr.io/zskarteaks:${{ github.sha }}
    #     imagepullsecrets: |
    #       zskarteaksdockerauth
