apiVersion: apps/v1
kind: Deployment
metadata:
  name: $(imageName)
  labels:
    app: $(imageName)
    service: $(serviceLabel)
    stage: $(stage)
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: $(imageName)
      service: $(serviceLabel)
      stage: $(stage)
  template:
    metadata:
      labels:
        app: $(imageName)
        service: $(serviceLabel)
        stage: $(stage)
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: $(imageName)
        image: $(fullImageName)
        startupProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 60
          failureThreshold: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 3
          periodSeconds: 5
        env:
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: db_host
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: db_port
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: db_name
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: db_user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: db_password
        - name: DATABASE_SSL
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: db_ssl
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: redis_host
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: redis_port
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: redis_password
        - name: STORAGE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: storage_account
        - name: STORAGE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: storage_account_key
        - name: STORAGE_URL
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: storage_url
        - name: STORAGE_CONTAINER_NAME
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: storage_container_name
        - name: ADMIN_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: admin_jwt_secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: jwt_secret
        - name: MICROSOFT_AUTH_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: microsoft_auth_tenant_id
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: node_env
        - name: BASE_URL
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: base_url
        - name: NUXT_URL
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: nuxt_url
        - name: MAIL_HOST
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: mail_host
        - name: MAIL_USER
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: mail_user
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: strapi-envs
              key: mail_password
        - name: NODE_ENV
          value: production
        ports:
        - name: http
          containerPort: 1337
      imagePullSecrets:
      - name: $(imagePullSecretName)
